# Generated by Django 4.0.5 on 2022-06-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='tel',
            field=models.TextField(default=998956545456, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typ',
            name='type',
            field=models.TextField(default=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='persons_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
