# Generated by Django 4.0.5 on 2022-07-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_status_person_tel_typ_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Foydalanuvchi turi')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='persons_id',
        ),
        migrations.AddField(
            model_name='taskcontroll',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcontroll',
            name='status_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcontroll',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.task'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel',
            field=models.CharField(max_length=13),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.usertyp'),
        ),
    ]
