# Generated by Django 4.0.5 on 2022-07-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_usertyp_remove_person_persons_id_taskcontroll_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typ',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
