# Generated by Django 4.0.5 on 2022-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_task_name_alter_typ_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcontroll',
            name='emp_count',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
