# Generated by Django 4.0.5 on 2022-07-13 14:16

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_task_info_taskcontroll_emp_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcontroll',
            name='data',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
