# Generated by Django 4.0.5 on 2022-07-19 19:14

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_taskcontroll_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcontroll',
            name='data',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
