# Generated by Django 4.0.5 on 2022-07-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_taskcontroll_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcontroll',
            name='emp_count',
        ),
        migrations.AddField(
            model_name='taskcontroll',
            name='emp_count',
            field=models.ManyToManyField(to='person.person'),
        ),
    ]
