# Generated by Django 4.0.5 on 2022-07-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_auth_images_name_alter_person_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
